server {
    listen 80;
    client_max_body_size 20M;
    resolver 127.0.0.11 valid=10s;

    set $backend http://backend:8000;

    location /api/docs/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/redoc.html;
    }

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass $backend;
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass $backend;
    }

    location /s/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass $backend;
    }

    location /media/ {
        alias /media/;
    }

    location / {
        root /staticfiles;
        index index.html;
        try_files $uri /index.html;
    }
}